language: node_js
node_js:
- '8'
cache:
  directories:
  - "node_modules"

install:
- "npm install"
- "npm run build"
script:
- nohup npm run dev &
- sleep 3
- npm run test
- npm run lint
deploy:
  provider: heroku
  api_key: dff45af8-4ec0-4cfd-b506-ffe6e7cc91c5
    secure: API_KEY
  app: dry-inlet-76991