language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run dev &
- sleep 3
- npm run test
- npm run lint
deploy:
  provider: heroku
  api_key: "szpvnp77*"
    secure: API_KEY
  app: dry-inlet-76991